package Vista;

import Modelo.ListaUsuarios;
import Modelo.Usuario;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JDesktopPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * @author mircosx
 */
public class VistaGConsultaUsuarios extends javax.swing.JInternalFrame implements GestionarModelo {

    UsuariosTableModel usuariosTableModel;
    VistaGFichaUsuario vGFichaUsuario;
    Usuario usuarioMain;
    private JDesktopPane jDesktopPane;

    public VistaGConsultaUsuarios(JDesktopPane jDesktopPane) {
        this.jDesktopPane = jDesktopPane;
        initComponents();
        inicializaComponentesPropios();
    }

    private void inicializaComponentesPropios() {
        vGFichaUsuario = new VistaGFichaUsuario(usuarioMain);
        jDesktopPane.add(vGFichaUsuario);
        jButtonDetalles.setVisible(false);
    }

    @Override
    public void fijarModelo(Object object) {
        usuariosTableModel = new UsuariosTableModel((ListaUsuarios) object);
        jTableUsuarios.setModel(usuariosTableModel);
        jTableUsuarios.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

    }

    @Override
    public UsuariosTableModel obtenerModelo() {
        return usuariosTableModel;
    }

    @Override
    public void limpiarModelo() {
        usuariosTableModel = null;
    }

    @Override
    public void setEditable(boolean esEditable) {
        usuariosTableModel.setEditable(esEditable);
    }

    class UsuariosTableModel extends DefaultTableModel {

        ListaUsuarios listaUsuariosLocal;
        boolean editable = true;
        Object[] encabezado = {"DNI", "E-Mail", "Nombre", "Apellido"};
        //private Collection<Titulo> titulos;
        private ArrayList<Usuario> listaUsuarios = new ArrayList<Usuario>();

        public UsuariosTableModel(ListaUsuarios listaUsuariosEntrada) {
            super();
            listaUsuariosLocal = listaUsuariosEntrada;
            Collection<Usuario> listado = listaUsuariosLocal.getListaUsuarios().values();
            System.out.println("hai " + listado.size() + " usuarios en VistaGConsultaUsuarios");
            Object data[][] = new Object[listado.size()][encabezado.length];

            int i = 0;
            for (Usuario usuario : listado) {
                int j = 0;
                data[i][j++] = usuario.getDni();
                data[i][j++] = usuario.getEmail();
                data[i][j++] = usuario.getNombre();
                data[i][j++] = usuario.getApellido1();
                listaUsuarios.add(usuario);
                i++;
            }
            setDataVector(data, encabezado);
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            if (!editable) {
                return false;
            } else {
                return super.isCellEditable(rowIndex, columnIndex);
            }
        }

        public void addUsuario(Usuario usuario) {
            //titulos.add(titulo);
            listaUsuarios.add(usuario);
        }

        public Usuario getUsuario(int pos) {
            return listaUsuarios.get(pos);
        }

        public boolean isEditable() {
            return editable;
        }

        public void setEditable(boolean editable) {
            System.out.println("editable:" + editable);
            this.editable = editable;
        }
    }

    public void setModo(String modo) {

        if (modo.equals("mostrar")) {
            setEditable(false);
            jButton2.setText("Ok");
        } else if (modo.equals("alta")) {
            usuarioMain = null;
            limpiarModelo();
            setEditable(true);
            setTitle("Alta de titulo");
            jButton2.setText("Alta");
        } else if (modo.equals("modificar")) {
            setEditable(true);
            setTitle("Modificación de titulo");
            jButton2.setText("Guardar");
        } else if (modo.equals("borrar")) {
            setEditable(false);
            setTitle("Eliminación de titulo");

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jButtonDetalles = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);

        jButtonDetalles.setText("Detalles");
        jButtonDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetallesActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");

        jButton3.setText("Nuevo");

        jButton4.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButtonDetalles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDetalles)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetallesActionPerformed
        
        vGFichaUsuario.setModo("mostrar");
        int filaSeleccionada = jTableUsuarios.getSelectedRow();
        System.out.println(filaSeleccionada);
        if (filaSeleccionada > -1) {
        System.out.println("--:" + usuariosTableModel.getUsuario(filaSeleccionada));
        vGFichaUsuario.fijarModelo(usuariosTableModel.getUsuario(filaSeleccionada));
        //vGFichaTitulo.setEditable(false);
        vGFichaUsuario.setVisible(true);
        }
         
        
    }//GEN-LAST:event_jButtonDetallesActionPerformed

    private void jTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseClicked
        int pos = jTableUsuarios.getSelectedRow();
        boolean visible = pos > -1 ? true : false;
        jButtonDetalles.setVisible(visible);        // asignar a una variable el valor de la fila de la tabla selecionada
    }//GEN-LAST:event_jTableUsuariosMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonDetalles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    // End of variables declaration//GEN-END:variables
}
